server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://sqlserver:1433;databaseName=hospital_account;encrypt=false;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:Your_strong_Password123!}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

hospital:
  account:
    seed:
      admin-username: ${HOSPITAL_ADMIN_USERNAME:admin}
      admin-email: ${HOSPITAL_ADMIN_EMAIL:admin@hopital.local}
      admin-password: ${HOSPITAL_ADMIN_PASSWORD:admin123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
