server:
  port: 8085

spring:
  application:
    name: laboratory-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://sqlserver:1433;databaseName=hospital_laboratory;encrypt=false;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:Your_strong_Password123!}
  flyway:
    locations: classpath:db/migration
    sql-migration-separator: _
    validate-migration-naming: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
