global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets: ["kong:8001"]

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:8080"]

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8088"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["account-service:8082"]

  # Add future Spring Boot hospital services here.
