package com.hopital.pharmacy.application.dto;

import com.hopital.pharmacy.application.domain.Currency;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Immutable pharmacy-side source data for the accounting posting generated by
 * a prescription delivery.
 *
 * <p>The accounting service should use {@code dispenseCode} as its external
 * idempotency key for the stock-cost side of the posting.</p>
 */
public record PrescriptionDispenseAccountingReferenceResponse(
        String dispenseCode,
        UUID hospitalId,
        String hospitalCode,
        BigDecimal totalCost,
        Currency currency,
        Instant occurredAt,
        List<PrescriptionDispenseAccountingLineResponse> lines) {
}
