package com.hopital.patient.application.domain;

public enum PatientAuditEventType {
    CREATED,
    TRANSFER_REQUESTED,
    TRANSFER_DISPATCHED,
    TRANSFER_RECEIVED,
    TRANSFER_CANCELLED,
    UPDATED,
    STATUS_CHANGED,
    TRIAGE_RECORDED,
    CLINICAL_ENTRY_ADDED,
    PRESCRIPTION_ADDED,
    PRESCRIPTION_DISPENSED,
    DOCUMENT_ADDED,
    DOCUMENT_REMOVED,
    IMPORTED
}
