server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URI:http://account-service:8082}
          predicates:
            - Path=/api/v1/accounts/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI:http://notification-service:8083}
          predicates:
            - Path=/api/v1/notifications/**
        - id: organization-service
          uri: ${ORGANIZATION_SERVICE_URI:http://organization-service:8084}
          predicates:
            - Path=/api/v1/organizations/**
        - id: laboratory-service
          uri: ${LABORATORY_SERVICE_URI:http://laboratory-service:8085}
          predicates:
            - Path=/api/v1/laboratory/**
        - id: patient-service
          uri: ${PATIENT_SERVICE_URI:http://patient-service:8086}
          predicates:
            - Path=/api/v1/patients/**
        - id: pharmacy-service
          uri: ${PHARMACY_SERVICE_URI:http://pharmacy-service:8089}
          predicates:
            - Path=/api/v1/pharmacy/**
        - id: personnel-service
          uri: ${PERSONNEL_SERVICE_URI:http://personnel-service:8087}
          predicates:
            - Path=/api/v1/personnel/**

management:
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
