server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URI:http://account-service:8082}
          predicates:
            - Path=/api/v1/accounts/**

management:
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
