package com.hopital.patient.application.dto;

import com.hopital.patient.application.domain.PaymentCurrency;
import com.hopital.patient.application.domain.PrescriptionDispenseCompletion;
import com.hopital.patient.application.domain.PrescriptionPaymentMethod;
import com.hopital.patient.application.domain.PrescriptionSource;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Immutable patient-side source data for the accounting posting generated by
 * one pharmacy delivery.
 *
 * <p>The accounting service should use {@code dispenseId} as the stable
 * external idempotency key for the receipt side. The matching pharmacy stock
 * cost can be retrieved with the same {@code dispenseCode} from the internal
 * pharmacy contract.</p>
 */
public record PharmacyDispenseAccountingReferenceResponse(
        UUID dispenseId,
        String dispenseCode,
        UUID hospitalId,
        String hospitalCode,
        UUID patientId,
        String patientCode,
        UUID passageId,
        String passageCode,
        UUID prescriptionId,
        String prescriptionCode,
        PrescriptionSource prescriptionSource,
        PrescriptionDispenseCompletion completion,
        BigDecimal totalAmount,
        BigDecimal paidAmount,
        PaymentCurrency currency,
        PrescriptionPaymentMethod paymentMethod,
        Instant dispensedAt,
        String dispensedByUserId,
        String dispensedByUsername,
        List<PharmacyDispenseAccountingLineResponse> lines) {
}
